spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    in.bachatsetu.backend: DEBUG
