spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

bachatsetu:
  tenancy:
    default-tenant-id: ${TENANT_DEFAULT_ID}
  persistence:
    auditing:
      system-actor-id: ${AUDIT_SYSTEM_ACTOR_ID}

management:
  endpoint:
    health:
      show-details: when_authorized
