ALTER TABLE audit.audit_entries DROP CONSTRAINT ck_audit_entries_event_type;

ALTER TABLE audit.audit_entries ADD CONSTRAINT ck_audit_entries_event_type CHECK (event_type IN (
    'LOGIN', 'LOGOUT', 'OTP_SENT', 'OTP_VERIFIED',
    'GROUP_CREATED', 'GROUP_UPDATED', 'GROUP_CLOSED',
    'MEMBER_ADDED', 'MEMBER_REMOVED',
    'PAYMENT_CREATED', 'PAYMENT_VERIFIED', 'PAYMENT_REFUNDED',
    'DRAW_CREATED', 'DRAW_COMPLETED',
    'RECEIPT_GENERATED', 'PDF_DOWNLOADED',
    'NOTIFICATION_SENT',
    'FILE_UPLOADED', 'FILE_DELETED',
    'GATEWAY_REFUND_INITIATED', 'GATEWAY_WEBHOOK_PROCESSED',
    'ADMIN_ANALYTICS_VIEWED',
    'SYSTEM_EVENT'
));
