ALTER TABLE identity.users
    ADD COLUMN city VARCHAR(100),
    ADD COLUMN state VARCHAR(100),
    ADD COLUMN photo_file_id UUID,
    ADD COLUMN notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN onboarded BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE audit.audit_entries DROP CONSTRAINT ck_audit_entries_event_type;

ALTER TABLE audit.audit_entries ADD CONSTRAINT ck_audit_entries_event_type CHECK (event_type IN (
    'LOGIN', 'LOGOUT', 'OTP_SENT', 'OTP_VERIFIED',
    'GROUP_CREATED', 'GROUP_UPDATED', 'GROUP_CLOSED',
    'MEMBER_ADDED', 'MEMBER_REMOVED',
    'PAYMENT_CREATED', 'PAYMENT_VERIFIED', 'PAYMENT_REFUNDED',
    'DRAW_CREATED', 'DRAW_COMPLETED',
    'RECEIPT_GENERATED', 'PDF_DOWNLOADED',
    'NOTIFICATION_SENT',
    'FILE_UPLOADED', 'FILE_DELETED',
    'GATEWAY_REFUND_INITIATED', 'GATEWAY_WEBHOOK_PROCESSED',
    'ADMIN_ANALYTICS_VIEWED',
    'PLATFORM_CONFIGURATION_UPDATED', 'FEATURE_FLAG_UPDATED', 'SYSTEM_LIMIT_UPDATED',
    'USER_REGISTERED', 'PROFILE_COMPLETED',
    'INVITATION_CREATED', 'INVITATION_REVOKED',
    'GROUP_JOINED', 'QR_JOINED', 'LINK_JOINED',
    'SYSTEM_EVENT'
));
