package in.bachatsetu.backend.infrastructure.persistence.adapter;

import in.bachatsetu.backend.shared.domain.AggregateId;
import java.util.UUID;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

/**
 * Provides a fixed, well-known placeholder tenant for local development and QA only.
 *
 * <p>Authentication's pre-login repository adapters ({@link AuthUserRepositoryAdapter},
 * {@link RoleRepositoryAdapter}, {@link UserRepositoryAdapter}) are tenant-scoped, but no request
 * carries a tenant identifier during login/OTP flows, and no real multi-tenant resolution
 * strategy (header, subdomain, or similar) has been designed yet. Returning one fixed tenant
 * unblocks local development and matches the data generated by the local seed loader. This is a
 * deliberate local-only stopgap, not a substitute for real tenant resolution, and must never be
 * active outside the "local" profile.
 */
@Configuration(proxyBeanMethods = false)
@Profile("local")
public class LocalTenantScopeProviderConfig {

    /** Placeholder tenant shared by every locally seeded record. */
    public static final AggregateId DEFAULT_TENANT_ID =
            new AggregateId(UUID.fromString("00000000-0000-0000-0000-000000000000"));

    @Bean
    TenantScopeProvider localTenantScopeProvider() {
        return () -> DEFAULT_TENANT_ID;
    }
}
